### ISSUE TITLE
"pnpm astro add @qwikdev/astro"  error

### ISSUE THREAD

**Issue by declanchiu** [QwikDev/astro#51] opened 2024-01-11 09:18 UTC
![image](https://github.com/QwikDev/astro/assets/55419399/0db15cef-e61e-480c-a364-30240a7c038b)

![image](https://github.com/QwikDev/astro/assets/55419399/61e3a965-cd6d-462b-8193-bf6fcba90cff)

**Comment by thejackshelton** [comment] 2024-01-12 17:28
Interesting, I wasn't able to reproduce your issue. Were you using a specific Astro template?

**Comment by thejackshelton** [comment] 2024-01-16 02:39
Let me know if you still have this issue! Closing. This uses Astro's CLI feature, and seems to be working with pnpm for me currently.

**Closed by thejackshelton** 2024-01-16 02:39 UTC

**Comment by declanchiu** [comment] 2024-01-17 11:11
> Interesting, I wasn't able to reproduce your issue. Were you using a specific Astro template?有趣的是，我无法重现您的问题。您使用的是特定的 Astro 模板吗？

Thank you for your response. I surmise that network-related factors might have been at play. The configuration in astro.config was the initialized default without any alterations. Presently, the issue no longer presents itself.
