### ISSUE TITLE
 error occurred in windows 11 environment.

### ISSUE THREAD

**Issue by ngadceser** [QwikDev/astro#33] opened 2023-11-24 23:21 UTC
import qwikdev from '@qwikdev/astro';

// https://astro.build/config
export default defineConfig({
  integrations: [
    tailwind({
      applyBaseStyles: false,
    }),
    qwikdev(),
  ],
});
----------------------------------
When I build on windows 11, I get the following error: I did not create a qwik sample.

 Path contains invalid characters: \D:\foldername\dist\
  File:
    D:\foldername\node_modules\fs-extra\lib\mkdirs\utils.js:16:21
  Code:
    15 |     if (pathHasInvalidWinCharacters) {
    > 16 |       const error = new Error(`Path contains invalid characters: ${pth}`)
         |                     ^
      17 |       error.code = 'EINVAL'
      18 |       throw error
      19 |     }
  Stacktrace:
After commenting out qwikdev(), the build succeeds.
---
Each build will continue to create a folder of the form .tmp-o0bk86ikj2l.

I experimented again and it doesn't build regardless of the node.

**Comment by thejackshelton** [comment] 2023-11-24 23:39
Will need a reproduction of the issue, wasn't able to reproduce it on windows 11.

**Comment by thejackshelton** [comment] 2023-11-25 00:12
Ah I think I might know what the problem is, you're using the `D` drive, but we are only replacing the `C` drive 🤦‍♂️ 

Will see what I can do to fix that

**Comment by thejackshelton** [comment] 2023-11-25 00:32
@ngadceser try 0.2.4

**Comment by ngadceser** [comment] 2023-11-25 02:49
I'm surprised you got to it so quickly, thank you. I ran 0.2.4 after giving it a try, and it works really well. Thanks again.

**Comment by thejackshelton** [comment] 2023-11-25 03:24
Glad to hear it! Closing.

**Closed by thejackshelton** 2023-11-25 03:24 UTC
