### ISSUE TITLE
Actual value for useContext() can not be found

### ISSUE THREAD

**Issue by RaoulBivolaru** [QwikDev/astro#36] opened 2023-11-27 15:10 UTC
Not sure if is something wrong with my code but I cannot manage to setup a context. I get an error saying that the context value cannot be found:

<img width="1181" alt="Screenshot 2023-11-27 at 17 06 44" src="https://github.com/QwikDev/astro/assets/6637816/0c2880a2-3525-4a72-8e0c-94bb5a784006">

Minimal Demo with Stackblitz: https://stackblitz.com/edit/withastro-astro-cwqlod

Any help is much appreciated.

**Comment by thejackshelton** [comment] 2023-11-28 16:53
Took a quick look at this, will get back to it when I'm available.

For starters, I think you need to wrap your validate and onSubmit handler function in a QRL.

You can think of a QRL as a lazy loaded function

https://qwik.builder.io/docs/advanced/qrl/#qrl

**Comment by thejackshelton** [comment] 2023-12-05 22:06
Took a second look and can confirm that context is working properly when consuming a Qwik UI component. There's an error about missing types from that package, but that's another story.

https://github.com/thejackshelton/qwik-ui-astro-scratch

It looks like the issue is in useFields, where there are no props being passed to form, and your context is expecting those values. If I remove the useFields hook and its properties, then the component works.

Going to close this for now, if you find that there is in fact an issue with context I'm happy to look at a minimal reproduction.

**Closed by thejackshelton** 2023-12-05 22:06 UTC
